[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FastSTR"
version = "1.0.0"
description = "FastSTR: A high-performance tool for short tandem repeat (STR) detection and analysis from genome assemblies."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Wen Long", email = "wenlong2024@mail.nwpu.edu.cn" }
]
maintainers = [
    { name = "Wen Long", email = "wenlong2024@mail.nwpu.edu.cn" }
]
keywords = ["tandem repeat", "STR", "genome", "bioinformatics", "sequence alignment"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent"
]

# 项目依赖
dependencies = [
    "biopython==1.83",
    "numpy==1.26.0",
    "pandas==2.2.2",
    "regex==2024.9.11",
    "scikit-learn==1.5.2"
]


# 命令行工具入口（FastSTR命令）
[project.scripts]
faststr = "faststr.main:main"

[project.urls]
Homepage = "https://github.com/XL-BioGroup/FastSTR"
Repository = "https://github.com/XL-BioGroup/FastSTR"
Issues = "https://github.com/XL-BioGroup/FastSTR/issues"

# 可选：自定义 setuptools 设置
[tool.setuptools.packages.find]
where = ["."]
include = ["faststr*"]
exclude = ["tests*"]


